---
title: "Replication Code for Local Governance and Green Ties"
author: "Michael D. Siciliano"
institute: Networks and Governance Lab, University of Illinois Chicago
format: html
editor: source
---

## Libraries and Data

```{r}
#| echo: true

library(tidyverse)
library(patchwork)
library(gtsummary)
library(modelsummary)
library(marginaleffects)

dat = read_csv("data/green_ties_data.csv")
```

Create logged versions of variables

```{r}
#| echo: true

dat = dat %>% mutate(
  med_hh_income_2019_log = log(med_hh_income_2019),
  total_pop2019_log = log(total_pop2019.x),
  genrev2017.pc.dollars.log = log(genrev2017.pc.dollars)
)

```


## Descriptive Table

```{r}
#| echo: true

stats <- c("Mean (SD)" = "{mean} ({sd})", 
           "Range (Min, Max)" = "{min}, {max}")

desc.table <- 
  purrr::imap(
  stats,
  ~ dat %>%
    tbl_summary(
    include = c(ev_netsize, flood_netsize, tot_ev_units, tot_fl_units, dedicated.staffing,
                centralized.staffing, grantwriter_dummy, funding_internal, funding_external,
                med_hh_income_2019_log, total_pop2019_log, genrev2017.pc.dollars.log, pct_dem_2016),
    type = list(dedicated.staffing ~ 'continuous',
                centralized.staffing ~ 'continuous',
                grantwriter_dummy ~ 'continuous',
                funding_internal ~ 'continuous',
                funding_external ~ 'continuous'),
    label = c(ev_netsize ~ "External Network Size - EV",
              flood_netsize ~ "External Network Size - Flooding",
              tot_ev_units ~ "Internal Collaboration - EV",
              tot_fl_units ~ "Internal Collaboration - FLooding",
              dedicated.staffing ~ "Dedicated Staff",
              centralized.staffing ~ "Centralized Staff",
              grantwriter_dummy ~ "Grant Writer",
              funding_internal  ~ "Internal Funding",
              funding_external ~ "External Funding",
              med_hh_income_2019_log ~ "Log of Median Household Income",
              total_pop2019_log ~ "Log of Total Population",
              genrev2017.pc.dollars.log ~ "Log of Per Capita Revenue",
              pct_dem_2016 ~ "Percent of 2016 Vote that was Democratic"),
    missing = "no", #to not show count of NA values
    digits = everything() ~ 2,
    statistic = ~.x)  %>%
    modify_header(all_stat_cols() ~ stringr::str_glue("**{.y}**"))
) %>%
  tbl_merge(tab_spanner = FALSE) %>%
  modify_footnote(~NA)
desc.table
```



## Figures

```{r}
#| echo: true

ev1 = ggplot(dat, aes(x = ev_netsize)) + geom_bar(fill = "darkgrey", alpha = .8) + 
  labs(y = "Count",
       x = "EV Network Size") +
  theme_bw() + 
    theme(text = element_text(size = 12))

fl1 = ggplot(dat, aes(x = flood_netsize)) + geom_bar(fill = "darkgrey", alpha = .8) + 
  labs(y = "Count",
       x = "Flood Network Size") +
  theme_bw() + 
  theme(text = element_text(size = 12))

ev1 + fl1 
```



## Electric Vehicle Models

QuasiPoisson Models:

```{r}
#| echo: true

mod1.ev = glm(ev_netsize ~ tot_ev_units + dedicated.staffing, data = dat, family = quasipoisson(link = "log"))

mod2.ev = glm(ev_netsize ~ tot_ev_units + dedicated.staffing + 
                grantwriter_dummy + 
                funding_external + 
                funding_internal + med_hh_income_2019_log + 
                total_pop2019_log + genrev2017.pc.dollars.log +
                pct_dem_2016, 
              data = dat, family = quasipoisson(link = "log"))

mod3.ev = glm(ev_netsize ~ tot_ev_units + dedicated.staffing +
                tot_ev_units:centralized.staffing +
                grantwriter_dummy + 
                funding_external + 
                funding_internal + med_hh_income_2019_log + 
                total_pop2019_log + genrev2017.pc.dollars.log +
                pct_dem_2016, 
              data = dat, family = quasipoisson(link = "log"))


mod4.ev = glm(ev_netsize ~ tot_ev_units + dedicated.staffing + 
                dedicated.staffing:centralized.staffing +
                grantwriter_dummy + 
                funding_external + 
                funding_internal + med_hh_income_2019_log + 
                total_pop2019_log + genrev2017.pc.dollars.log +
                pct_dem_2016, 
              data = dat, family = quasipoisson(link = "log"))



modelsummary(list("EV - 1" = mod1.ev, "EV - 2" = mod2.ev, 
                  "EV - 3" = mod3.ev, "EV - 4" = mod4.ev),
             estimate = "{estimate} ({std.error}) {stars}",
             statistic = NULL,
             stars = T, fmt = 2,
             align="lllll",
             coef_rename = c(
               "tot_ev_units" = "Internal Collaboration - EV",
               "tot_fl_units" = "Internal Collaboration - FLooding",
               "dedicated.staffing" = "Dedicated Staff",
               "centralized.staffing" = "Centralized Staff",
               "grantwriter_dummy" = "Grant Writer",
               "funding_internal" = "Internal Funding",
               "funding_external" = "External Funding",
               "med_hh_income_2019_log" = "Log of Median Household Income",
               "total_pop2019_log" = "Log of Total Population",
               "genrev2017.pc.dollars.log" = "Log of Per Capita Revenue",
               "pct_unemployed" = "Percent Unemployed",
               "pct_dem_2016" = "Percent Democratic Vote"))
```

Average Marginal Effects:

```{r}
#| echo: true

mx.mod3.ev = slopes(mod3.ev)
modelsummary(mx.mod3.ev,
             estimate = "{estimate} ({std.error}) {stars}",
             statistic = NULL,
             stars = T, fmt = 2,
             coef_rename = c(
              "tot_ev_units" = "Internal Collaboration - EV",
              "tot_fl_units" = "Internal Collaboration - Flooding",
              "dedicated.staffing" = "Dedicated Staff",
              "centralized.staffing" = "Centralized Staff",
              "grantwriter_dummy" = "Grant Writer",
              "funding_internal" = "Internal Funding",
              "funding_external" = "External Funding",
              "med_hh_income_2019_log" = "Log of Median Household Income",
              "total_pop2019_log" = "Log of Total Population",
              "genrev2017.pc.dollars.log" = "Log of Per Capita Revenue",
              "pct_unemployed" = "Percent Unemployed",
              "pct_dem_2016" = "Percent Democratic Vote"))


#update model output above to capture the interaction effects
slopes(mod4.ev, variables = "dedicated.staffing", 
                by = "centralized.staffing")

slopes(mod3.ev, variables = "tot_ev_units", 
                by = "centralized.staffing")
```



## Flooding Models

QuasiPoisson Models:

```{r}
#| echo: true

mod1.fl = glm(flood_netsize ~ tot_fl_units + dedicated.staffing, data = dat, family = quasipoisson(link = "log"))

mod2.fl = glm(flood_netsize ~ tot_fl_units + dedicated.staffing + 
                grantwriter_dummy + 
                funding_external + 
                funding_internal + med_hh_income_2019_log + 
                total_pop2019_log + genrev2017.pc.dollars.log +
                pct_dem_2016, 
              data = dat, family = quasipoisson(link = "log"))

mod3.fl = glm(flood_netsize ~ tot_fl_units + dedicated.staffing + 
                tot_fl_units:centralized.staffing +
                grantwriter_dummy + 
                funding_external + 
                funding_internal + med_hh_income_2019_log + 
                total_pop2019_log + genrev2017.pc.dollars.log +
                pct_dem_2016, 
              data = dat, family = quasipoisson(link = "log"))


mod4.fl = glm(flood_netsize ~ tot_fl_units + dedicated.staffing + 
                dedicated.staffing:centralized.staffing +
                grantwriter_dummy + 
                funding_external + 
                funding_internal + med_hh_income_2019_log + 
                total_pop2019_log + genrev2017.pc.dollars.log +
                pct_dem_2016, 
              data = dat, family = quasipoisson(link = "log"))


modelsummary(list("Flood - 1" = mod1.fl, "Flood - 2" = mod2.fl, 
                  "Flood - 3" = mod3.fl, "Flood - 4" = mod4.fl), 
             estimate = "{estimate} ({std.error}) {stars}",
             statistic = NULL,
             stars = T, fmt = 2,
             align="lllll",
             coef_rename = c(
               "tot_ev_units" = "Internal Collaboration - EV",
               "tot_fl_units" = "Internal Collaboration - Flooding",
               "dedicated.staffing" = "Dedicated Staff",
               "centralized.staffing" = "Centralized Staff",
               "grantwriter_dummy" = "Grant Writer",
               "funding_internal" = "Internal Funding",
               "funding_external" = "External Funding",
               "med_hh_income_2019_log" = "Log of Median Household Income",
               "total_pop2019_log" = "Log of Total Population",
               "genrev2017.pc.dollars.log" = "Log of Per Capita Revenue",
               "pct_unemployed" = "Percent Unemployed",
               "pct_dem_2016" = "Percent Democratic Vote"))

```



Average Marginal Effects: 

```{r}
#| echo: true

mx.mod2.fl = slopes(mod2.fl)
modelsummary(mx.mod2.fl,
             estimate = "{estimate} ({std.error}) {stars}",
             statistic = NULL,
             stars = T, fmt = 2,
             coef_rename = c(
              "tot_ev_units" = "Internal Collaboration - EV",
              "tot_fl_units" = "Internal Collaboration - Flooding",
              "dedicated.staffing" = "Dedicated Staff",
              "centralized.staffing" = "Centralized Staff",
              "grantwriter_dummy" = "Grant Writer",
              "funding_internal" = "Internal Funding",
              "funding_external" = "External Funding",
              "med_hh_income_2019_log" = "Log of Median Household Income",
              "total_pop2019_log" = "Log of Total Population",
              "genrev2017.pc.dollars.log" = "Log of Per Capita Revenue",
              "pct_unemployed" = "Percent Unemployed",
              "pct_dem_2016" = "Percent Democratic Vote"))

#update model output above to capture the interaction effects
slopes(mod3.fl, variables = "dedicated.staffing", 
                by = "centralized.staffing")
```

